In [15]:
import torch 
import torchvision 
import torch.nn as nn 
import numpy as np 

In [14]:
x = torch.tensor(
    [1,2,3,4], 
    dtype=torch.float32
)


outputs = torch.softmax(x, dim=0)
print('outputs are : ', outputs)


tensor([1., 2., 3., 4.])
outputs are :  tensor([0.0321, 0.0871, 0.2369, 0.6439])


tensor(1.)

In [31]:
# cross entropy  = -1/n Sum(yi.log(yi_^))


loss = nn.CrossEntropyLoss()

y_true = torch.tensor([0,2,1])

good = torch.tensor([0])


y_pred_good = torch.tensor([
    [4.0, 2.0, 0.1],
    [0.3, 0.7, 2], 
    [0.2,2.2,0.9]
])


y_pred_bad = torch.tensor([
    [2.0, 0.2, 0.1],
    [0.3, 0.7, 0.1], 
    [0.2,0.1,0.9]
])


# batchsize stuff 
l1 = loss(y_pred_good, y_true)
l2 = loss(y_pred_bad, y_true)


print('l1 = ', l1.item())
print('l2 = ', l2.item())

l1 =  0.2872765362262726
l2 =  1.0455279350280762


> :warning: The y_hat should not be one hot encoded 
> becauset nn.CrossEntropyLoss uses LogSoftmax and NLLLoss (negative likelihood loos)
> no softmax in last layer 
> Y has class label on hot encoded 
> Y_pred has raw scores (logits), no softmax

In [33]:
_, prediction1 = torch.max(y_pred_good, 1) # returns actual values and their indices
# this means apply the max function every time in the dimension 1, 
_, prediction2 = torch.max(y_pred_bad, 1)

print(prediction1)

tensor([0, 2, 1])
tensor([4.0000, 2.0000, 2.2000])


# neural network 

In [35]:
import torch 
import torch.nn 
import numpy 
import torchvision 

In [ ]:
class NeuralNet2(nn.Module): 

    def __init__(self, input_size, hidden_size, num_classes) -> None:
        super(NeuralNet2, self).__init__()

        self.linear1 = nn.linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(hidden_size, num_classes)


    def forward(self, x):
        out = self.linear(x)
        out = self.relu(x)
        out = self.linear2(x) 
        # no softmax here 

        return out 

model = NeuralNet2(input_size=28*28, hidden_size=5, num_classes=3)
criterion = nn.CrossEntropyLoss() # applies softmax



# with binary cross entropy we need to add the sigmoid function at the end 

In [ ]:
# we will just change the model where the output size is 1, and we add the sigmoid function, 
# the criterion will be the binary cross entropy loss
# nn.BCELoss