In [ ]:



"""Tensor basics 

- watch the pytorch sheatcheet it's very amazing 
- I think athat anything numpy does also torch does it.

-BEFORE EVERYTHING : The minimum dimension you'll be working with it 2d at min.
no tensors of shpae (,5)


- METHODS:
    - torch.cuda_is_avialable() -> Bool 
        checks if cuda is available 
        
    - torch.from_numpy(np_array) -> Torch tensor of the np_array 
    - torch.view(new_shape) 
        behaves same as np.reshape()
        
    - torch.empty(shape) -> tensor of shape 
        careful this methods retuns some stuff that are not 
        created at the first place 

    - torch.zeros(shape) -> Tensor 
    - torch.ones(shape) - > Tensor
    - torch.tensor(array|np_array, dtype:torch.float32...etc) -> Tensor

    
"""

In [1]:
import torch 

tensor([0.], requires_grad=True)

# Tensor basics 

In [3]:
# empty tenor 
x = torch.empty(1)
x

tensor([9.2755e-39])

In [4]:
x = torch.empty((2,3,4))
x

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
x = torch.zeros(5)
x

tensor([0., 0., 0., 0., 0.])

In [8]:
x.dtype

torch.float32

In [9]:
# basically I can see them as numpy array to 
x = torch.ones(4)

In [10]:
x.size()

torch.Size([4])

In [11]:
torch.tensor([2.0,2.5])

tensor([2.0000, 2.5000])

In [12]:
torch.rand(2,2)

tensor([[0.5157, 0.5165],
        [0.5632, 0.7545]])

In [13]:
# we can do addition etc
x = torch.rand(2,2)
y = torch.rand(2,2)

z= x - y 
z = torch.sub(x,y)
z

tensor([[ 0.0589, -0.6246],
        [ 0.5025, -0.0638]])

In [17]:
mul = torch.mul(x,y)
mul

div = torch.div(x,y)
print(div)

tensor([[1.1166, 0.2387],
        [2.3516, 0.8603]])


In [19]:
tensor = torch.rand(5,3)

tensor[0:3, 1:3]

tensor([[0.7978, 0.4739],
        [0.6001, 0.3249],
        [0.7865, 0.2432]])

In [21]:
tensor[1,1].item()
# this returns the actual value 

0.6000868678092957

In [28]:
x = torch.rand(4,4)
y = x.view(16)
y = x.view(-1,8)

print(y.size())

torch.Size([2, 8])


In [29]:
nump_arr = y.numpy()

> :warning: Be careful wth memory location if you have b = a.numpy() and then you change a, you will also see that b has changes, since they point to the same memory location

In [37]:
import numpy as np 

a = np.ones(5)
print(a)

b = torch.from_numpy(a)
print(b)

a += 1 

print('a after modification ', a)
print('b after modification ', b)
# here also the b will be changes lol 


if (torch.cuda.is_available()): 
    print('available')
    device = torch.device('cuda')
    x = torch.ones(5, device = device) # this will make it on the gpu 
    y = torch.ones(5)
    y = y.to(device) 
    z = x + y # this might be faster since it's on the gpu 

    z.numpy() # this will return an error since numpy can handle only CPU tensors
    # you cannot convert a gpu tensor to cpu 

    z = z.to('cpu') # this will return it to cpu    
else: 
    print('not availabel')





[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
a after modification  [2. 2. 2. 2. 2.]
b after modification  tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
not availabel


In [ ]:
x = torch.ones(5, require_grad=True) # this will tell pytorch that we need it to calculate gradienst in optimization
print(x)