In [3]:
# auto grad package in pytorch: 
"""
Methods: 
        - torch.tensor(..., requires_grad = True)
        - W.grad : to get the gradients
        - W.grad.zero_() : resets the gradients to zero 
        - torch.softmax(tensor, dim): dim is the axis you want to apply to 

Infos: 
        y = x +2, and x has required_grad => y will have grad_function
def int(){
        print('soemthing to do here right ')
        print('this is another thing to do here right?')
}


Super infos: 
        a tensor has 
                .data
                .grad (the actual dl/dw)
                .grad_fn
                .is_leaf
                .requires_grad
"""
print()

In [5]:
import torch 

In [12]:
x = torch.tensor([1,2,3,4], dtype=torch.float16, requires_grad=True)

# this will create a computational graph 
y = x + 2
print(y)

z = y * y*2 # this tensor will have also the grad thing 
z = z.mean()
# you will see the AddBackward function , so that we can do the back propagation later
print('z' , z)

z.backward() # dz/dx
print('x.grad', x.grad)

tensor([3., 4., 5., 6.], dtype=torch.float16, grad_fn=<AddBackward0>)
z tensor(43., dtype=torch.float16, grad_fn=<MeanBackward0>)
x.grad tensor([3., 4., 5., 6.], dtype=torch.float16)


In [4]:
x = torch.tensor([2.0, 3.0], requires_grad=True)

y = torch.pow(x, 2) +1 
print(y)

y[0].backward() # this only works for scalar outpu

tensor([ 5., 10.], grad_fn=<AddBackward0>)


In [31]:
x.grad # I guess this actually returns dy/dx

tensor([4., 0.])

In [ ]:
y = x.detach 
y # here same but doens't require the gradient 

with torch.no_grad() : # this disables the autograd
    y = x + 2 
    # now y will not have grad function 
    pass

<function Tensor.detach>

In [5]:
weighs = torch.ones(4, requires_grad=True)

In [6]:
import torch 

In [7]:
weighs = torch.tensor([1,2,3,4,5,6,7,8,9], dtype=torch.float32, requires_grad=True)
# require_grad will say that weighs are considered parameters of df/dw
# whatever the F function that will use the weighs 

for epoch in range(2): 
    model_output =  torch.pow(weighs, 2).sum()

    model_output.backward() # this will calculate do/dw

    print(weighs.grad)# ici normalemnet on aura le

    weighs.grad.zero_() # set gadients to zero, so that in the next step it will not accumulate 



tensor([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])
tensor([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])


In [8]:
import torch 


weights = torch.ones(4, dtype=torch.float32,  requires_grad=True) # we need to specify this 
optimizer = torch.optim.SGD([weights ], lr=0.01)

optimizer.step() # update the weights 

optimizer.zero_grad()

weights.grad

In [12]:
# pytorch is amazing, and then you're going to add up on hugging face you will put it together
# how is this going to be optimized for the research ?

x = torch.tensor(5)
x

import torchvision


tensor(5)