In [ ]:
"""
Sometimes we can consider some weight for unbalance data 
"""




In [4]:
import torch
import torch.nn as nn 
import torchvision 
import torchvision.datasets as datasets

from torch.utils.data import DataLoader
from torchvision.transforms import transforms
import numpy as np 

In [ ]:
# create and prepare the datasets 
root ='./data'

# 1. Download the dataset 
# I already downloaded the dataset so no need to see 
train_dataset = datasets.CIFAR10(root=root, train=True, download=True)
val_dataset = datasets.CIFAR10(root=root, train=False, download=True)


# 2. Load the dataset 

# first define the transfomrations 
mean = np.array([0.5, 0.5, 0.5])
std = np.array([0.25, 0.25, 0.25])

transformations = transforms.Compose([
    transforms.Resize((224,224)), 
    transforms.ToTensor(), 
    transforms.Normalize(mean, std)
])

# use ImageLoader 
train_dataset = datasets.ImageFolder(root='./data', transform=transformations) # I think it should be /data/train
val_dataset = datasets.ImageFolder(root='./data', transform=transformations) # I think it should be /data/val



# 3. Create data loader to iterate and batches 
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
valid_loader = DataLoader(val_dataset, batch_size=42, shuffle=True)




print('len of train_loader ', len(train_loader))
print('len of valid loader', len(valid_loader))

In [1]:

# training a CNN or other frameworks it' snot that deep 

import torch 
from torchvision import transforms

a = torch.tensor(
    [
        [1,2],
        [3,4]
    ]
)


a.flatten()

tensor([1, 2, 3, 4])

In [2]:
a.view(-1,4)

tensor([[1, 2, 3, 4]])

In [3]:
a.permute(1,0)

tensor([[1, 3],
        [2, 4]])

In [16]:
preds = torch.randn((2,2))
torch.max(preds,1)

torch.return_types.max(
values=tensor([1.8015, 0.7795]),
indices=tensor([1, 0]))

In [ ]:
# that's it the PHD yo'ure working alot on numerical analysis and shit you feel me bruh.
# Transformer based application for making the self attention in the NLP world you feel me bruh.Thank you so much
# Let me be your apprentice if you would like so man. Okay?
# i hope so dude lol, see you later by the way if you can help me too; lol.